services:
  - type: web
    name: json-server
    runtime: node # Defines the runtime environment as Node.js
    plan: free
    buildCommand: "npm install"
    startCommand: "json-server --watch db.json --port 3000"
    envVars:
      - key: NODE_ENV
        value: production
